# Generated by Django 4.1 on 2023-03-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choise_text',
        ),
    ]
